export const Users = [
  {
    id: 1,
    profilePicture: "images/1.jpeg",
    username: "Naresh Chowdary",
  },
  {
    id: 2,
    profilePicture: "images/2.jpeg",
    username: "Joe Root",
  },
  {
    id: 3,
    profilePicture: "images/3.jpeg",
    username: "Paul Walker",
  },
  {
    id: 4,
    profilePicture: "images/4.jpeg",
    username: "Sk Rossi",
  },
  {
    id: 5,
    profilePicture: "images/5.jpeg",
    username: "Emma Watson",
  },
  {
    id: 6,
    profilePicture: "images/6.jpeg",
    username: "Olivia Paul",
  },
  {
    id: 7,
    profilePicture: "images/7.jpeg",
    username: "Ean Bell",
  },
  {
    id: 8,
    profilePicture: "images/8.jpeg",
    username: "Rokki Dan",
  },
  {
    id: 9,
    profilePicture: "images/9.jpeg",
    username: "Sam Prasad",
  },
  {
    id: 10,
    profilePicture: "images/10.jpeg",
    username: "Rahul Tej",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Hey Dexter what's Up dude😄.",
    photo: "uploads/1.jpeg",
    date: "1 min ago",
    userId: 1,
    like: 22,
    comments: 5,
  },
  {
    id: 2,
    photo: "uploads/2.jpeg",
    date: "3 min ago",
    userId: 2,
    like: 9,
    comments: 1,
  },
  {
    id: 3,
    photo: "uploads/3.jpeg",
    date: "5 min ago",
    userId: 3,
    like: 15,
    comments: 12,
  },
  {
    id: 4,
    photo: "uploads/4.jpeg",
    date: "6 min ago",
    userId: 4,
    like: 11,
    comments: 6,
  },
  {
    id: 5,
    photo: "uploads/5.jpeg",
    date: "8 min ago",
    userId: 5,
    like: 23,
    comments: 13,
  },
  {
    id: 6,
    photo: "uploads/6.jpeg",
    date: "10 min ago",
    userId: 6,
    like: 19,
    comments: 16,
  },
  {
    id: 7,
    photo: "uploads/7.jpeg",
    date: "14 min ago",
    userId: 7,
    like: 23,
    comments: 1,
  },
  {
    id: 8,
    photo: "uploads/8.jpeg",
    date: "16 min ago",
    userId: 8,
    like: 21,
    comments: 21,
  },
  {
    id: 9,
    photo: "uploads/9.jpeg",
    date: "18 min ago",
    userId: 8,
    like: 29,
    comments: 19,
  },
  {
    id: 10,
    photo: "uploads/10.jpeg",
    date: "21 min ago",
    userId: 10,
    like: 49,
    comments: 31,
  },
];
